build_order:
  - platforms: win32
    packages:
    - strawberryperl
    - msys2
    - winflexbison
  - platforms: "*"
    packages:
    - audacity_build_helpers
    - ninja
    - gn
    - nasm
    - yasm
    - meson
    - m4
    - autoconf
    - automake
    - pkgconf
  - platforms: linux
    packages:
    - openssl
  - platforms: "*"
    packages:
    - zlib
    - zstd
    - brotli
    - bzip2
    - sqlite3
    - libpng
    - md4c
    - pcre2
    - double-conversion
    - libjpeg-turbo
    - icu
    - freetype
    - harfbuzz
    - libcurl
    - ogg
    - flac
    - opus
    - opusfile
    - vorbis
    - mpg123
    - libmp3lame
    - libsndfile
    - threadpool
    - rapidjson
    - catch2
    - expat
    - portaudio
    - portmidi
    - vst3sdk
    - wavpack
    - breakpad
    - crashpad
    - libtiff
    - wxwidgets
