packages:
  audacity_build_helpers: '*'
  autoconf: '*'
  automake: '*'
  bison: '*'
  breakpad: '*'
  brotli: '*'
  bzip2: '*'
  catch2: '*'
  crashpad: '*'
  double_conversion: '*'
  expat: '*'
  flac: '*'
  flex: '*'
  fontconfig: '*'
  freetype: '*'
  gn: '*'
  gnu-config: '*'
  gperf: '*'
  harfbuzz: '*'
  icu: '*'
  kddockwidgets: '*'
  libcurl: '*'
  libid3tag: '*'
  libjpeg-turbo: '*'
  libmad: '*'
  libmp3lame: '*'
  libpng: '*'
  libsndfile: '*'
  libtiff: '*'
  libtool: '*'
  libtorch-binary: '*'
  libuuid: '*'
  linux-syscall-support: '*'
  list.txt: '*'
  m4: '*'
  md4c: '*'
  meson: '*'
  mpg123: '*'
  msys2: '*'
  nasm: '*'
  ninja: '*'
  ogg: '*'
  openssl: '*'
  opus: '*'
  opusfile: '*'
  patchelf: '*'
  pcre2: '*'
  pkgconf: '*'
  portaudio: '*'
  portmidi: '*'
  qt: '*'
  qt-tools: '*'
  rapidjson: '*'
  sqlite3: '*'
  strawberryperl: '*'
  threadpool: '*'
  vorbis: '*'
  vst3sdk: '*'
  wavpack: '*'
  winflexbison: '*'
  wxwidgets: '*'
  zlib: '*'
  zstd: '*'
  yasm: '*'
