name: Build Audacity Dependencies

on:
  workflow_dispatch:
    inputs:
      audacity_repo:
        description: Audacity Repository
        required: true
        default: audacity/audacity
      audacity_ref:
        description: Audacity Branch or Tag
        required: true
        default: master
jobs:
  build:
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_HOST: ${{ secrets.SENTRY_HOST }}
      SENTRY_ORG_SLUG: ${{ secrets.SENTRY_ORG_SLUG }}
      SENTRY_PROJECT_SLUG: ${{ secrets.SENTRY_PROJECT_SLUG }}
      ARTIFACTORY_SYMBOLS_URL: ${{ secrets.ARTIFACTORY_SYMBOLS_URL }}
      ARTIFACTORY_SYMBOLS_KEY: ${{ secrets.ARTIFACTORY_SYMBOLS_KEY }}
      CONAN_BINARIES_REMOTE: ${{ secrets.CONAN_BINARIES_REMOTE }}
      CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_LOGIN_USERNAME }}
      CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Ubuntu_20.04
          os: audacity-ubuntu-20.04
          arch: x64
          generator: Unix Makefiles
          build_type: RelWithDebInfo
        - name: Ubuntu_20.04_Debug
          os: audacity-ubuntu-20.04
          arch: x64
          generator: Unix Makefiles
          build_type: Debug

        - name: Ubuntu_22.04
          os: audacity-ubuntu-22.04
          arch: x64
          generator: Unix Makefiles
          build_type: RelWithDebInfo
        - name: Ubuntu_22.04_Debug
          os: audacity-ubuntu-22.04
          arch: x64
          generator: Unix Makefiles
          build_type: Debug

        - name: Windows_32bit_2019
          os: audacity-windows-latest
          arch: x32
          generator: Visual Studio 16 2019
          build_type: RelWithDebInfo

        - name: Windows_64bit_2019
          os: audacity-windows-latest
          arch: x64
          generator: Visual Studio 16 2019
          build_type: RelWithDebInfo

        - name: Windows_32bit_2022
          os: audacity-windows-latest
          arch: x32
          generator: Visual Studio 17 2022
          build_type: RelWithDebInfo

        - name: Windows_64bit_2022
          os: audacity-windows-latest
          arch: x64
          generator: Visual Studio 17 2022
          build_type: RelWithDebInfo
    steps:
    - name: Checkout Audacity
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.audacity_repo }}
        ref: ${{ github.event.inputs.audacity_ref }}
    - name: Setup dependencies
      uses: audacity/audacity-actions/dependencies@v1
    - name: Configure
      uses: audacity/audacity-actions/configure@v1
      with:
        generator: ${{ matrix.config.generator }}
        configuration_types: Debug;Release;RelWithDebInfo;MinSizeRel
        build_type: ${{ matrix.config.build_type }}
        arch: ${{ matrix.config.arch }}
        cmake_options:
          -Daudacity_enable_experimental_qt_support=ON
    - name: Cleanup Conan files
      shell: bash
      run: |
        conan remove "*" -f
