name: Build Audacity Dependencies (macOS)

on:
  workflow_dispatch:
    inputs:
      audacity_repo:
        description: Audacity Repository
        required: true
        default: audacity/audacity
      audacity_ref:
        description: Audacity Branch or Tag
        required: true
        default: master
  push:

jobs:
  build:
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_HOST: ${{ secrets.SENTRY_HOST }}
      SENTRY_ORG_SLUG: ${{ secrets.SENTRY_ORG_SLUG }}
      SENTRY_PROJECT_SLUG: ${{ secrets.SENTRY_PROJECT_SLUG }}
      ARTIFACTORY_SYMBOLS_URL: ${{ secrets.ARTIFACTORY_SYMBOLS_URL }}
      ARTIFACTORY_SYMBOLS_KEY: ${{ secrets.ARTIFACTORY_SYMBOLS_KEY }}
      CONAN_BINARIES_REMOTE: ${{ secrets.CONAN_BINARIES_REMOTE }}
      CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_LOGIN_USERNAME }}
      CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Xcode_13.2.1 (x86_x64)
          os: audacity-macos
          arch: x64
          generator: Xcode
          build_type: RelWithDebInfo
          xcode_version: 13.2.1
        - name: Xcode_13.2.1 (Arm64)
          os: audacity-macos
          arch: arm64
          generator: Xcode
          build_type: RelWithDebInfo
          xcode_version: 13.2.1
        - name: Xcode_14.0.1 (x86_x64)
          os: audacity-macos
          arch: x64
          generator: Xcode
          build_type: RelWithDebInfo
          xcode_version: 14.0.1
        - name: Xcode_14.0.1 (Arm64)
          os: audacity-macos
          arch: arm64
          generator: Xcode
          build_type: RelWithDebInfo
          xcode_version: 14.0.1

    steps:
    - name: Checkout Audacity
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.inputs.audacity_repo }}
        ref: ${{ github.event.inputs.audacity_ref }}
    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.config.xcode_version }}
    - name: Setup dependencies
      shell: bash
      run: |
        brew install conan
    - name: Configure
      uses: audacity/audacity-actions/configure@v1
      with:
        generator: ${{ matrix.config.generator }}
        configuration_types: Debug;Release;RelWithDebInfo;MinSizeRel
        build_type: ${{ matrix.config.build_type }}
        arch: ${{ matrix.config.arch }}
        cmake_options:
          -Daudacity_enable_experimental_qt_support=ON
    - name: Cleanup Conan files
      shell: bash
      run: |
        conan remove "*" -f
